[DEFAULT]
test_number = 6
process_number = 32
dataset_dir = /home/chenlu/ChatUniTest_GPT3.5/dataset_batch/Csv_1_b
result_dir = /home/chenlu/ChatUniTest_GPT3.5/results_batch/Csv_1_b
project_dir = /home/chenlu/ChatUniTest_GPT3.5/defect4j_projects/Csv_1_b
max_rounds = 6
TIMEOUT = 30
MAX_PROMPT_TOKENS = 2700
MIN_ERROR_TOKENS = 500
PROMPT_TEMPLATE_NO_DEPS = d1_4.jinja2
PROMPT_TEMPLATE_DEPS = d3_4.jinja2
PROMPT_TEMPLATE_ERROR = error_3.jinja2

LANGUAGE = java
GRAMMAR_FILE = /home/chenlu/ChatUniTest_GPT3.5/dependencies/tree-sitter-java/java-grammar.so
COBERTURA_DIR = /home/chenlu/ChatUniTest_GPT3.5/dependencies/cobertura-2.1.1
JUNIT_JAR = /home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/junit-platform-console-standalone-1.9.2.jar
MOCKITO_JAR = /home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/mockito-core-3.12.4.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/mockito-inline-3.12.4.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/mockito-junit-jupiter-3.12.4.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/byte-buddy-1.14.4.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/byte-buddy-agent-1.14.4.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/objenesis-3.3.jar
LOG4J_JAR = /home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/slf4j-api-1.7.5.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/slf4j-log4j12-1.7.12.jar:/home/chenlu/ChatUniTest_GPT3.5/dependencies/lib/log4j-1.2.17.jar
JACOCO_AGENT = /home/chenlu/ChatUniTest_GPT3.5/dependencies/jacoco/jacocoagent.jar
JACOCO_CLI = /home/chenlu/ChatUniTest_GPT3.5/dependencies/jacoco/jacococli.jar
REPORT_FORMAT = xml


[openai]
api_keys = ["sk-muOTUdBS9VAnJNLfvLoy47gJTDzH6QCdobSlCvWb9MSXPLRn"]
; api_keys = ["sk-kWxSjyJbml5nKqMv9x0qmbjy6aYnIZZcYNErKChSke5JIhJ9"]
model = gpt-3.5-turbo
temperature = 0.5
top_p = 1
frequency_penalty = 0
presence_penalty = 0
OLLAMA_URL = http://127.0.0.1:8328/v1/chat/completions
LLAMA3_MODEL = "llama3:8b"
OLLAMA_TIMEOUT = 3000

[database]
# host = 127.0.0.1
port = 3307
unix_socket = /home/chenlu/mysql/tmp/mysql.sock
database = chatunitest  
user = root
password = cl041204

